"""empty message

Revision ID: 47142945e03c
Revises: b47897dfb1c3
Create Date: 2021-07-28 14:31:04.364396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47142945e03c'
down_revision = 'b47897dfb1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_shows_association')
    op.drop_table('artist_shows_association')
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'])
    op.drop_column('Show', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Show_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_table('artist_shows_association',
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='artist_shows_association_artist_id_fkey'),
    sa.ForeignKeyConstraint(['show_id'], ['Show.id'], name='artist_shows_association_show_id_fkey'),
    sa.PrimaryKeyConstraint('artist_id', 'show_id', name='artist_shows_association_pkey')
    )
    op.create_table('venue_shows_association',
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['Show.id'], name='venue_shows_association_show_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='venue_shows_association_venue_id_fkey'),
    sa.PrimaryKeyConstraint('venue_id', 'show_id', name='venue_shows_association_pkey')
    )
    # ### end Alembic commands ###
